import './globals.scss';
import type { Metadata } from 'next';
import { Inter, Rubik } from 'next/font/google';

// Opting out of Data Caching because we're using cookies and authentication
// https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#opting-out-of-data-caching
export const dynamic = 'force-dynamic';

const inter = Inter({ subsets: ['latin'] });
const rubik = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Dojo Helpdesk',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`RootLayout bg-secondary container px-4 py-5 ${rubik.className}`}
			>
				{children}
			</body>
		</html>
	);
}

